# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{beer_mapping}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Phil McClure"]
  s.date = %q{2010-06-19}
  s.description = %q{Allows you to find where pubs are, how they are rating etc.}
  s.email = %q{phil.mcclure@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/beer_mapping.rb",
     "lib/beer_mapping/API.rb",
     "lib/beer_mapping/geo.rb",
     "lib/beer_mapping/image.rb",
     "lib/beer_mapping/location.rb",
     "lib/beer_mapping/rating.rb"
  ]
  s.homepage = %q{http://github.com/overture8/beer_mapping}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby wrapper for beermapping.com}
  s.test_files = [
    "test/test_beer_mapping.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

